### ISSUE TITLE
custom subcommands to create issues of a certain type

### ISSUE THREAD

**Issue by gwennlbh** [gwennlbh/issurge#33]
for example, `issurge bug ...` is equivalent to `issurge new ~bug ...`
we could make it really flexible so that you can define anything as essentially an alias for "adding words in front of what you'll type"

maybe it a config file?

```toml
[aliases]
bug = "~bug"
myfault = "~bug @me"
```

something like that

and then you do 

```
issurge myfault foo
```

and it runs `issurge new ~bug @me foo`
